src/reports/urls.py
from django.urls import path
from .views import (
    create_report_view,
    ReportListView,
    ReportDetailView,
    UploadTemplateView,
    render_pdf_view,
    csv_upload_view
)

app_name = 'reports'

urlpatterns = [
    path('', ReportListView.as_view(), name='main'),
    path('save/', create_report_view, name='create-report'),
    path('upload/', csv_upload_view, name='upload'),
    path('from_file/', UploadTemplateView.as_view(), name='from-file'),
    path('<pk>/', ReportDetailView.as_view(), name='detail'),
    path('<pk>/pdf/', render_pdf_view, name='pdf'),
]

src/sales/urls.py
from django.urls import path
from .views import (
    home_view,
    SalesListView,
    SaleDetailView,
)

app_name = 'sales'

urlpatterns = [
    path('', home_view, name='home'),
    path('sales/', SalesListView.as_view(), name='list'),
    path('sales/<pk>/', SaleDetailView.as_view(), name='detail'),
]

src/sales_reports/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sales.urls', namespace='sales')),
    path('reports/', include('reports.urls', namespace='reports')),
    path('my_profile/', include('profiles.urls', namespace='profiles')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/reports/models.py
from django.db import models
from django.urls import reverse

from profiles.models import Profile

class Report(models.Model):
    name = models.CharField(max_length=120)
    image = models.ImageField(upload_to='reports', blank=True)
    remarks = models.TextField()
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('reports:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return f"{self.name}"

    class Meta:
        ordering = ('-created_at',)

src/reports/forms.py
from django import forms
from .models import Report

class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ('name', 'remarks')

src/reports/views.py
import csv

from django.conf import settings
from django.contrib.staticfiles import finders
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.template.loader import get_template
from django.views.generic import ListView, DetailView, TemplateView
from django.utils.dateparse import parse_date
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from profiles.models import Profile
from sales.models import Sale, Position, CSV
from products.models import Product
from customers.models import Customer

from .models import Report
from .forms import ReportForm
from .utils import get_report_image

from xhtml2pdf import pisa

class ReportListView(LoginRequiredMixin, ListView):
    model = Report
    template_name = 'reports/main.html'


class ReportDetailView(LoginRequiredMixin, DetailView):
    model = Report
    template_name = 'reports/detail.html'

class UploadTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'reports/from_file.html'

@login_required
def csv_upload_view(request):
    if request.method == 'POST':
        csv_file_name = request.FILES.get('file').name
        csv_file = request.FILES.get('file')
        obj, created = CSV.objects.get_or_create(file_name=csv_file_name)

        if created:
            obj.csv_file = csv_file
            obj.save()
            with open(obj.csv_file.path, 'r') as f:
                reader = csv.reader(f)
                reader.__next__()
                for row in reader:
                    
                    row.pop()
                    
                    transaction_id = row[1]
                    product = row[2]
                    quantity = int(row[3])
                    customer = row[4]
                    date = parse_date(row[5])

                    try:
                        product_obj = Product.objects.get(name__iexact=product)
                    except Product.DoesNotExist:
                        product_obj = None

                    if product_obj is not None:
                        customer_obj, _ = Customer.objects.get_or_create(name=customer)
                        salesman_obj = Profile.objects.get(user=request.user)
                        position_obj = Position.objects.create(product=product_obj, quantity=quantity, created_at=date)

                        sale_obj, _ = Sale.objects.get_or_create(transaction_id=transaction_id, customer=customer_obj, salesman=salesman_obj, created_at=date)
                        sale_obj.positions.add(position_obj)
                        sale_obj.save()

                return JsonResponse({'ex': False})

        return JsonResponse({'ex': True})

    return HttpResponse()


"""
def create_report_view(request):
    if request.is_ajax():
        
        name = request.POST.get('name')
        remarks = request.POST.get('remarks')
        image = request.POST.get('image')

        img = get_report_image(image)

        author = Profile.objects.get(user=request.user)
        Report.objects.create(name=name, remarks=remarks, image=img, author=author)
        return JsonResponse({'msg': 'send'})
    return JsonResponse({'msg': 'not ajax'})
"""
@login_required
def create_report_view(request):
    form = ReportForm(request.POST or None)
    if request.is_ajax():

        image = request.POST.get('image')
        img = get_report_image(image)
        author = Profile.objects.get(user=request.user)

        if form.is_valid():
            instance = form.save(commit=False)
            instance.image = img
            instance.author = author
            instance.save()
        
        return JsonResponse({'msg': 'send'})
    return JsonResponse({'msg': 'not ajax'})

@login_required
def render_pdf_view(request, pk):

    template_path = 'reports/pdf.html'
    # obj = Report.objects.get(id=pk)
    obj = get_object_or_404(Report, pk=pk)
    context = {'obj': obj}
    
    response = HttpResponse(content_type='application/pdf')

    # If download
    # response['Content-Disposition'] = 'attachment; filename="report.pdf"'

    # If display
    response['Content-Disposition'] = 'filename="report.pdf"'
    
    template = get_template(template_path)
    html = template.render(context)

    pisa_status = pisa.CreatePDF(
       html, dest=response)
    
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')

    return response

src/reports/templates/reports/detail.html
{% extends "base.html" %}

{% block title %}
    {{object.name}}
{% endblock title %}

{% block content %}
    {% if object.image %}

        <div class="column box">
            <figure class="image">
                <img src="{{object.image.url}}" alt="{{object.name}}">
            </figure>
        </div>
        <div class="column">
            <h3 class="subtitle">Remarks</h3>
            <p>{{object.remarks}}</p>
            <hr>
            <p>Author: <strong>{{object.author.user.username}}</strong><br>
            Created: <strong>{{object.created_at}}</strong></p>
        </div>
    {% endif %}
{% endblock content %}

src/reports/templates/reports/from_file.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
<script src="{% static 'reports/upload.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
    Upload sales files
{% endblock title %}

{% block content %}
    <h3 class="subtitle">Upload your sales documents</h3>
    <br>
    <div id="alert-box"></div>
    <form id="upload-dropzone" class="dropzone dz">
        {% csrf_token %}
        <div class="fallback">
            <input name="file" type="file" multiple />
        </div>
    </form>
{% endblock content %}

src/reports/templates/reports/main.html
{% extends "base.html" %}

{% block title %}
Reports
{% endblock title %}

{% block content %}
Reports
<hr>
<br>
{% for obj in object_list %}

    <div class="card mb-5">
        <div class="card-image">
            <figure class="image">
            <img src="{{obj.image.url}}" alt="{{obj.name}}">
            </figure>
        </div>
        <div class="card-content">
            <div class="media">
            <div class="media-left">
                <figure class="image is-48x48">
                <img src="{{obj.author.profiles.avatar}}" alt="">
                </figure>
            </div>
            <div class="media-content">
                <p class="title is-4">{{obj.name}}</p>
                <p class="subtitle is-6">{{obj.author}}</p>
            </div>
            </div>

            <div class="content">
                <p>{{obj.remarks|truncatewords:10}}</p>
            </div>
        </div>
        <div class="buttons mb-5 ml-5">
            <a style="text-decoration:none;" href="{{obj.get_absolute_url}}" class="button is-success">View details</a>
            <a target="_blank" style="text-decoration:none;" href="{% url 'reports:pdf' obj.pk %}" class="button is-danger">Print as PDF</a>
        </div>
    </div>
{% endfor %}
{% endblock content %}

src/reports/templates/reports/pdf.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>PDF {{obj.name}}</title>
  <style>
  </style>
</head>
<body>
    <h1 class="title">{{obj.name}}</h1>
    <hr>
    <img src="{{obj.image.path}}" class="image">
    <br>
    <h3 class="subtitle">Remarks</h3>
    <p>{{obj.remarks}}</p>
    <hr>
    <p>Author: <strong>{{obj.author.user.username}}</strong>
    <br>Created: <strong>{{obj.created_at}}</strong></p>
</body>
</html>